SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 1024

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

INITIAL_SCORE = 0
INITIAL_MULTIPLIER = 1
DEFAULT_POINTS = 10
MAX_MULTIPLIER = 4.0
MULTIPLIER_INCREASE = 0.5
MULTIPLIER_DECREASE = 0.25

ASTEROID_SIZE_LARGE = 'large'
ASTEROID_SIZE_MEDIUM = 'medium'
ASTEROID_SIZE_SMALL = 'small'
SCORE_VALUES = {
    'large': 20,
    'medium': 50,
    'small': 100
}
SPACESHIP = "spaceship"
PLAYER_INITIAL_ROTATION = 180
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500  
PLAYER_SHOOT_COOLDOWN = 0.3
SHOT_RADIUS = 5
SHIELD_DURATION = 5000
HEIGHT = 1440
